name: Trigger User Site rebuild

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="smith-ollie" 
          repo_name="smith-ollie.github.io"  
          event_type="trigger-workflow"

          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$repo_owner/$repo_name/dispatches \
            -f event_type="$event_type" \
            -f client_payload='{"service":"'$service'","version":"'$version'","unit":false,"integration":true}'
        env:
          GH_TOKEN: ${{ secrets.PAT }}
