name: Trigger User Site rebuild

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/smith-ollie/smith-ollie.github.io/dispatches \
            -f event_type='trigger-workflow'
        env:
          GH_TOKEN: ${{ secrets.PAT }}
